# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3e777c5a1153528a7c91a65890e5ce7972526e961a7d390f876ed09ee6e89f4840d4f0974059e715780c79b3aff95a19c08ef4cfa3b9e871de7dceecb804f6

test:
  secret_key_base: fc52e70d61b9385fa8ef94faa7368a25cbf68dbc39ccea44bf53dd5bf8fd55ec76829fef64e36e396e73076c359dff7c0fa970e5882610b924e685e1aa12a602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
